### ISSUE TITLE
Backend specific setup instruction should be moved to Readme inside backend Folder

### ISSUE THREAD

**Issue by zedjarvis** [OlePundit/Open-source#11]
The python and django setup should be moved inside the Readme in the backend folder. Similarly fronted specific setup will be inside Readme in the fronted folder. The main Readme should contain general description of the project and point to the two separate readme files in fronted folder and backed folder

**Comment by OkelloSam21** [comment]
Okay I'm eorking on updating this for the backend.

**Comment by OkelloSam21** [comment]
@zedjarvis I have moved the **Getting Started** part of the Readme to the backend readme
